# Generated by Django 2.2.5 on 2019-11-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191119_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='authror',
            new_name='author',
        ),
    ]
