# Generated by Django 2.2.5 on 2019-10-22 21:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
