# Generated by Django 2.2.5 on 2020-01-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191022_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
